### ISSUE TITLE
Avoid running `git config --global user.name`

### ISSUE THREAD

**Issue by vkarpov15** [mohammad0-0ahmad/ts-benchmark#6]
This line:

https://github.com/mohammad0-0ahmad/ts-benchmark/blob/80acbdcb5d147c9a1e80a03b86d3b714bdc49c4d/src/utilities/storageManager.ts#L47-L50

is a little risky if you're running ts-benchmark locally. Changing users' git config is very risky. For example, in this PR https://github.com/Automattic/mongoose/pull/12345 I had ts-benchmark change my git username and email.

**Comment by mohammad0-0ahmad** [comment]
@vkarpov15 yes, that is correct, I forget to make sure that the environment is GitHub instead of just checking if github flag is provided.
I will fix it soon, and I will invite you to this repo in case you found something need to be changed asap.
Sorry for troubles, and thanks for feedback
Please just update ts-benchmark version in [mongoose ](https://github.com/Automattic/mongoose)to 1.1.11 instead of 1.1.10
